server:
  servlet:
    context-path: /api
spring:
  application:
    name: mediumclone

  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:testdb?MODE=MYSQL;

  jpa:
    #show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop


